jobs:
  RunTests:
    name: Run Tests
    steps:
      - type: script
        docker-image: danieljgallo/flutter-builder
        script-content: dart ci/run_tests.dart
        name: Run Flutter tests
    runs-on: Linux-Medium
  BuildWeb:
    name: Build Web
    runs-on: Linux-Medium
    dependencies:
      - RunTests
    steps:
      - type: script
        docker-image: danieljgallo/flutter-builder
        name: Run Flutter web build
        script-content: flutter build web --base-href="/Flutter-2D-Game-Sample/"
    files-publication:
      - build/web/**/*
  BuildLinux:
    name: Build Linux
    runs-on: Linux-Medium
    dependencies:
      - RunTests
    steps:
      - type: script
        name: Run Flutter Linux build
        script-content: flutter build linux
        docker-image: danieljgallo/flutter-builder
    enable-dependency-cache: true
    files-publication:
      - build/linux/x64/release/bundle/**/*
  DeployWeb:
    name: Deploy Web
    runs-on: Linux-Medium
    dependencies:
      - BuildWeb:
          files:
            - build/web/**/*
    steps:
      - type: script
        name: Deploy to GitHub Pages
        script-content: >-
          git init


          git config user.email "%GitHubEmail%"

          git config user.name "TeamCity Bot"


          git remote add origin
          https://%GitHubToken%@github.com/%GitHubUsername%/Flutter-2D-Game-Sample.git


          # Checkout or reset to gh-pages branch

          if git show-ref --quiet refs/heads/gh-pages; then
            git checkout gh-pages
          else
            git checkout -b gh-pages
          fi


          git add .

          git commit -m "Deploy Flutter Web to GitHub Pages"

          git push --force origin gh-pages
        working-directory: build/web
secrets:
  GitHubToken: credentialsJSON:3bd4e308-010a-4955-9669-6dc7a40073d4
  GitHubEmail: credentialsJSON:eeb65406-8c92-4990-850e-53ccaa405b03
  GitHubUsername: credentialsJSON:c32aff10-8760-4fe1-b978-9e98b17616c8
